CREATE USER readonly_user WITH PASSWORD 'todolist';
GRANT CONNECT ON DATABASE postgres TO readonly_user;
GRANT USAGE ON SCHEMA public TO readonly_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_user;

CREATE USER rag_user WITH PASSWORD 'pass';
CREATE DATABASE rag_db OWNER rag_user;